### ISSUE TITLE
support for GA2M models/FAST/pairwise interactions (mltk)

### ISSUE THREAD

**Issue by rquintino** [dswah/pyGAM#122]
Hi wonder if supporting ga2m/fast is on the roadmap? thx!

Accurate Intelligible Models with Pairwise Interactions
www.cs.cornell.edu/~yinlou/papers/lou-kdd13.pdf
https://github.com/yinlou/mltk/wiki/Generalized-Additive-Models#ga2m
https://www.datarobot.com/blog/interpretability-and-accuracy-or-how-to-have-your-cake-and-eat-it-too/

**Comment by dswah** [comment]
@rquintino i was not aware of ga2m/fast algorithms. i'll give them a read.

The roadmap certainly includes GAMs with feature interactions via tensor products of splines.
I wonder if this is similar to ga2m?

**Comment by bglick13** [comment]
I would also definitely be interested in implementation of feature interactions

**Comment by syhuang-veolia** [comment]
Here's a link to ga2m model:vhttps://dl.acm.org/citation.cfm?id=2487579
Please please consider similar functions like in mgcv, such as s(x, by = z) in addition to the tensor products of spline.

**Comment by dswah** [comment]
@rquintino @bglick13 @syhuang-veolia
im sorry to say that for now GA2M and FAST are not on the feature roadmap.
the main reason is that these appear to require decision trees as the base learners, not spline functions.

however feature interactions are (slowly) in development!

**Comment by dswah** [comment]
@rquintino @bglick13 feature interactions are here! (pygam >= v0.6.0)
you can use tensor products to fit interactions using the `te()` function like so:

```python
GAM(te(0,1)).fit(X, y)
```
which fits a tensor product of splines on features 0 and 1.
you can also get more specific like so:

```python
GAM(te(s(0, n_splines=100), f(1))).fit(X, y)
```
which fits a tensor product between a spline-term with 100 basis functions for feature 0, and a factor term for feature 1.

@syhuang-veolia i've added by-variables so that you can make models like:

```python
GAM(s(0, by=1)).fit(X, y)
```
which fits a spline on feature 0, using feature 1 as a by-variable
