### ISSUE TITLE
Issues with examples...

### ISSUE THREAD

**Issue by conduit242** [dswah/pyGAM#138]
There seem to be a few issues with the examples provided which may confuse someone:
- The data sets are not actually loaded within the example code
- Simulation from the posterior does not appear to work for LinearGAMs. Particularly I get the error:
`AttributeError: 'LinearGAM' object has no attribute 'sample'`
- Matplotlib usage is 'fast and loose'. For example, it is not imported, plt.show() is assumed or interactive use is assumed, etc.
- Nice features like confidence_intervals are not demonstrated.
- There is no code at all for the 'Linear Extrapolation' section. It may be most useful to demonstrate this using a simple time series data set.

Wonderful work so far!

**Comment by conduit242** [comment]
My apologies, I just noticed there is an example of confidence intervals at the B-spline intro in the 'Regression' section.

**Comment by dswah** [comment]
@conduit242 all good points :) thank you for the feedback and the suggestions. 

-i think making some data loading code would be nice. that should be quick since the tests already do it. 
-agreed. a time series example would be very nice!
-the gam sampling has been merged but i havent gotten around to pushing the new release yet. i see you've forked the repo, so you should be able to use that feature in the mean time if you need. 
-agreed. plotting code cleanup would be nice.

**Comment by dswah** [comment]
missing pieces:

- [X] The data sets are not actually loaded within the example code
- [X] Simulation from the posterior does not appear to work for LinearGAMs. Particularly I get the error:
    AttributeError: 'LinearGAM' object has no attribute 'sample'
- [X] Nice features like confidence_intervals are not demonstrated.

- [ ] There is no code at all for the 'Linear Extrapolation' section. It may be most useful to demonstrate this using a simple time series data set.
- [ ] Matplotlib usage is 'fast and loose'. For example, it is not imported, plt.show() is assumed or interactive use is assumed, etc.

**Comment by dswah** [comment]
the docs have more complete code examples.
im happy closing this issue for now.

please re-open it if you think otherwise!
