### ISSUE TITLE
Constraints: "periodic smoothing [soon...]"

### ISSUE THREAD

**Issue by conduit242** [dswah/pyGAM#151]
How soon? :) I ask because this constraint would be quite useful for time series forecasting applications.

**Comment by conduit242** [comment]
Is this something in progress or could I help work on it?

**Comment by dswah** [comment]
@conduit242 Hi there! Sorry for taking so long to respond... (no excuse :)

This is feature is currently not in progress, and I would love your help in developing it.

perhaps we can start trading ideas in this thread?

**Comment by dswah** [comment]
i have some ideas of things that we would figure out when working on this:

## pretty easy:
- [ ] need to include `periodic` in somwhere the `__init__`method. perhaps in the `constraints` kwarg
- [ ] pass a boolean periodic kwarg to `utils. b_spline_basis` https://github.com/dswah/pyGAM/blob/master/pygam/utils.py#L535
- [ ] remove outdated and wrong `circular` constraint + constraint function
- [ ] introduce new `periodic` constraint and use `penalties.none` as its constraint function since we shouldn't enforce this constraint via an additional loss term, but instead via clever basis construction.

## harder
- [ ] if `periodic==True` in `utils. b_spline_basis` we need to assign the response the last few spline basis functions (i think few is equal to `spline_order`) and copy their response to the first few basis functions (although in reverse order?)
- [ ] if `periodic==True` in `utils. b_spline_basis` we need to take the modulus of x with the 2 edges in `edge_knots`

## things to decide
- [ ] do we require the user to specify the period of the variable? or do we just assume it to be the max and min knots of that variable in the training data?
- [ ] how do we treat fitting a line to a variable that we've flagged as periodic?

**Comment by dswah** [comment]
what do you think @conduit242 ?
also, i'm still not sure what the best way to collaborate is.
should you create a `periodic` branch in your fork and then we both push to it?

**Comment by conduit242** [comment]
Apologies, I was on an extended trip, I'll comment back soon :).

**Comment by dswah** [comment]
@conduit242 awesome. i just got back from a trip as well! 
im excited to collaborate on this!

**Comment by rsignell-usgs** [comment]
@dswah and @conduit242 , I came across this issue when trying to reproduce this [cool bird migration paper](http://rspb.royalsocietypublishing.org/content/283/1823/20152588) in Python.   My [first attempt at computing the centroids of each bird species for each day of the year](https://nbviewer.jupyter.org/gist/rsignell-usgs/002517245f44c2611e5c4625d96c867e) was a _bit_ noisy.

Here's how the authors cleaned up the mess:

> The mean of each coordinate was allowed to vary smoothly as a function of day of the year using a cyclic penalized B-spline, so the model smoothly joined daily location estimates made for 31 December and 1 January. 

So just another vote that this would be great!

I'm thinking I could probably fake this by simply copying part of the dataset onto each end and using non-cyclic p splines.    Think that would work?

**Comment by rsignell-usgs** [comment]
@dsway, I'm excited to see this progress and to try this.   Will report back soon I hope!
