### ISSUE TITLE
Improve compatibility with sklearn

### ISSUE THREAD

**Issue by AntonP84** [dswah/pyGAM#168]
`LogisticGAM` constructor lacks `verbose` parameter. So, its usage as part of sklearn `Pipeline` with `GridSearchCV` results in error

```
/usr/local/lib/python3.6/site-packages/sklearn/base.py in clone(estimator, safe)
     61     for name, param in six.iteritems(new_object_params):
     62         new_object_params[name] = clone(param, safe=False)
---> 63     new_object = klass(**new_object_params)
     64     params_set = new_object.get_params(deep=False)
     65 

TypeError: __init__() got an unexpected keyword argument 'verbose'
```

**Comment by dswah** [comment]
@AntonP84 ayyy thanks for pointing that out. looks like i forgot to add that argument to the GAM subclasses. 

could you try the same thing with the general GAM class?
`logistic_gam = GAM(distribution='binomial', link='logit', ...)`

this general class constructor has the verbose argument.

**Comment by dswah** [comment]
@AntonP84 awesome thanks for trying that out. 
how did that GridSearchCV work out?

im surprised that it appeared to work at all because looking at the sklearn docs it appears that pyGAM classes have a few things missing, like a `score()` method [1]. 

how did you do it?

[1] http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

**Comment by dswah** [comment]
wow, i was surprised to find that this indeed works, because sklearn lets you define a score function!
sweet!
