### ISSUE TITLE
Issue with generate_X_grid

### ISSUE THREAD

**Issue by stefano-m-potter** [dswah/pyGAM#228]
Hello,

I am trying to look at some partial dependence plots and I am trying to build a grid using:

from pygam.utils import generate_X_grid, but I get the error: Traceback (most recent call last):

  File "<ipython-input-6-58b7fe4be83a>", line 1, in <module>
    from pygam.utils import generate_X_grid

ImportError: cannot import name 'generate_X_grid

I looked in the utils.py file and I can't seem to find the generate_X_grid part of it?

**Comment by dswah** [comment]
hey @stefano-m-potter !

the problem is that we moved that function into a gam method. 

try instead:

```python
gam.generate_X_grid(term=...)
```

also please check out the quick-start guide for some more imformation!

https://pygam.readthedocs.io/en/latest/notebooks/quick_start.html

the tutorial on code-burst is out of date, and we should stop advertising it...
