### ISSUE TITLE
 y data is not in domain of link function?

### ISSUE THREAD

**Issue by mathcbc** [dswah/pyGAM#50]
X_train = np.array([1,2,3,4])
y_train = np.array([2,3,4,5])
gam = LogisticGAM()
gam.fit(X_train, y_train)

I run the above codes and raised an error"AssertionError: y data is not in domain of link function"
I don't know how to use your API.

**Comment by dswah** [comment]
Hi @mathcbc ,

Yes, this is because the LogisticGAM model is meant to operate on binary-valued y data, not real-valued y data.

If you want to perform regression, perhaps try LinearGAM.
```
# create a noisy parabola
x = np.linspace(-5, 5, 500)[:,None]
y = -.5 * x**2 + 5 + 2 * np.random.randn(len(x),1)

from pygam import LinearGAM
gam = LinearGAM()
gam.fit(x, y)
gam.summary()
```

Please note: 
you must give the model at least as many samples as the model has coefficients. 
for now, assume you need at least (n_knots + 5) samples.

i will work on adding those assertions soon.
