### ISSUE TITLE
can I use this project in time series prediction ?

### ISSUE THREAD

**Issue by mathcbc** [dswah/pyGAM#52]
I want to make predictions of time series. Can this project process time series data ?

**Comment by dswah** [comment]
@mathcbc
yes, of course, but it will only be capable of AR (auto-regressive) models, which is a reasonable place to start.

**Comment by dswah** [comment]
@mathcbc however, the package is still very immature. this is why i have no installation docs.
for example extrapolation is currently broken.

i would ask you to wait a few days before using the code.

**Comment by mathcbc** [comment]
AR models are linear so they are not what i want. Additive models have smooth functions of variable X_i, so they can solve nonlinear models. Do your algorithm contains smoother？

At 2017-03-11 02:01:49, "daniel servén" <notifications@github.com> wrote:


@mathcbc
yes, of course, but it will only be capable of AR (auto-regressive) models, which is a reasonable place to start.

**Comment by dswah** [comment]
Yes, the algorithm learns a smoother on each feature. 

What i mean is that you may want to choose the number of AR lags a-priori and structure your feature vector so that each lag is a feature. This way the GAM will learn a smoother for each lag.

In effect this is a sort of non-linear AR model:

`x_t = f_1(x_{t-1}) + f_2(x_{t-2}) + ... + f_p(x_{t-p}) + c`

just a thought. :)
